version: 0.0
os: linux
files:
  - source: build/libs/wedle-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/app/step1/zip/
    overwrite: yes
  - source: appspec.yml
    destination: /home/ubuntu/app/step1/zip/
    overwrite: yes
  - source: scripts
    destination: /home/ubuntu/app/step1/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 240
      runas: ubuntu
