spring:
  main:
    allow-bean-definition-overriding: true
  session:
    store-type: jdbc
  profiles:
    include: oauth
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

springdoc:
  packages-to-scan: yerong.wedle
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui-wedle.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  cache:
    disabled: true
